### ISSUE TITLE
v0.0.13 Tracking Issue 

### ISSUE THREAD

**Issue by gthao313** [bottlerocket-os/bottlerocket-test-system#897]
## v0.0.13
**Release captains 🧑‍✈️**
@gthao313  

**Targeting 🎯**

- [x] https://github.com/bottlerocket-os/bottlerocket-test-system/pull/895 

**Maintenance 🔧**
- [x] https://github.com/bottlerocket-os/bottlerocket-test-system/issues/896
- [x] [karpenter-agent-update](https://github.com/bottlerocket-os/bottlerocket-test-system/pull/898)
- [x] Dependabot alerts
